### ISSUE TITLE
Infinite Redirect Loop with Duende IdentityServer using Terraform Helm Provider on AWS Kubernetes

### ISSUE THREAD

**Issue by ghost** [Aguafrommars/helm#14]
## Summary:
I'm experiencing an infinite redirect loop when deploying [TheIdServer](https://github.com/Aguafrommars/TheIdServer) with Duende IdentityServer on a Kubernetes cluster in AWS (using Linux instances). The deployment is managed via the Terraform Helm provider.

## Details:

- **Expected Behavior:** After authenticating with Duende IdentityServer, I expect to be redirected back to my application's designated return URL and remain there.
  
- **Actual Behavior:** After authentication, I'm caught in an infinite loop of redirects between my application and TheIdServer.

- **Reproduction Steps:** 
  1. Followed the tutorial from [this link](https://github.com/Aguafrommars/TheIdServer/blob/master/src/Aguacongas.TheIdServer.Duende/README.md).
  2. Deployed TheIdServer on an AWS Kubernetes cluster (Linux instances) using Terraform Helm provider.
  3. Started the authentication process from my application.
  4. Completed the authentication on Duende IdentityServer.
  5. Observed the infinite redirect loop between the application and TheIdServer.

- **Environment & Configuration:** 
  - **OS:** AWS Kubernetes Cluster with Linux instances.
  - **Browser:** Predominantly on Chrome, but the issue is reproducible on other browsers as well.
  - **TheIdServer Version:** Using image `aguacongas/theidserver.duende:7.4.6`
  - **Terraform:** v1.6.2 on linux_amd64
  - **Providers:**
     - `registry.terraform.io/hashicorp/helm` v2.11.0
     - `registry.terraform.io/hashicorp/kubernetes` v2.23.0
     - `registry.terraform.io/hashicorp/random` v3.5.1
     - `registry.terraform.io/hashicorp/tls` v4.0.4
  - **Any custom configurations or setups, if any.**

## Additional Information:

1. I have ensured that the client application's redirect URL and post-logout redirect URL are correctly configured.
2. Cookie names have been checked for uniqueness to avoid any overlap.
4. The issue persists across different environments (dev, staging).

**Comment by lirei-uqtr** [comment]
Thank you, it works!
